### ISSUE TITLE
Just a doubt

### ISSUE THREAD

**Issue by sunilroyy007** [m4mallu/clonebot#29]
Heroku restarts every 24hours and sometimes randomly . In repo it said it will save a csv file so after restart we can start clone process again and it will ignore the files which are already cloned right. 
My doubt is does that csv file gets saved even if we dont use database in heroku or does it saved somewhere else permanently without database 🤔? As heroku database is not permanent

**Comment by m4mallu** [comment]
CSV files will be saved in the local file system so that changes in the database won't affect the indexed list. The name of the CSV file will be the chat id of the target chat. If a change in target chat will also create another CSV file in the name of the same. These CSV files will be inside the directory which is in the name of the user's user.id.

**Comment by sunilroyy007** [comment]
> CSV files will be saved in the local file system so that changes in the database won't affect the indexed list. The name of the CSV file will be the chat id of the target chat. If a change in target chat will also create another CSV file in the name of the same. These CSV files will be inside the directory which is in the name of the user's user.id.

Thanks for clarification. I have one more thing how do i change clone delay time by default it set to 10 seconds i want to change timer based on my usage like 30 seconds or 1 minute anything.
 I have changed in https://github.com/sunilroyy007/clonebot/blob/e3edbb19730acefe3026c342f1c4ef824e8a9a74/plugins/clone.py#L42 but whenever i activated clone delay it still works with 10seconds only.
